### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by mgiessing**
fixed incorrect lib prefix for centos/rhel

This PR should have no impact for the official ubuntu builds since the default libdir is already `lib`, but it helps for centos/rhel builds, because protobuf and prometheus-cpp default libdir is `lib64` which'll cause error in the full build.

### CODE REVIEW

**Comment by deadeyegoodwin** [comment]
So protobuf and prometheus use a different default libdir on centos?

**Comment by mgiessing** [comment]
Yes I was first confused when triton complained about missing protobuf-config.cmake and prometheus-cpp-config.cmake but then I figured out, that those two will get installed into lib64 by default whereas on ubuntu they'll default to lib.

Here's an example of centos8 output when I use this repo without the PR changes:

```
[root@57f6228969a1 build]# cmake -DTRITON_THIRD_PARTY_INSTALL_PREFIX=install ..
[...]

[root@57f6228969a1 build]# find / -name "proto*cmake"
/root/third_party/build/protobuf/tmp/protobuf-cache-.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib64/cmake/protobuf/protobuf-options.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib64/cmake/protobuf/protobuf-targets.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib64/cmake/protobuf/protobuf-config.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib64/cmake/protobuf/protobuf-module.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib64/cmake/protobuf/protobuf-targets-release.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib64/cmake/protobuf/protobuf-config-version.cmake
```

**Comment by mgiessing** [comment]
@deadeyegoodwin 
I actually wanted to show the comparison to ubuntu (which I forgot to include for some reason):

Here is essentially the same procedure on an ubuntu20.04 container and you can see that it defaults to `lib` compared to `lib64` on the centos build container in my previous post.

```
root@068fbf510b79:~/third_party/build# cmake -DTRITON_THIRD_PARTY_INSTALL_PREFIX=install ..
[...]

root@068fbf510b79:~/third_party/build# make -j160 protobuf
[...]

root@068fbf510b79:~/third_party/build# find / -name "proto*cmake"
/root/third_party/build/protobuf/tmp/protobuf-cache-.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib/cmake/protobuf/protobuf-options.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib/cmake/protobuf/protobuf-targets.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib/cmake/protobuf/protobuf-config.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib/cmake/protobuf/protobuf-module.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib/cmake/protobuf/protobuf-targets-release.cmake
/root/third_party/build/protobuf/src/protobuf-build/install/protobuf/lib/cmake/protobuf/protobuf-config-version.cmake
```

Does that answer your question adequately?

**Comment by deadeyegoodwin** [comment]
I understand now. Can you add a comment before each of those externproject_add explaining why we are overriding the default libdir

**Comment by mgiessing** [comment]
I added a comment to explain why the value gets overridden - if you need anything else let me know.

**Review by deadeyegoodwin — COMMENTED** [review]
Looks good. I just need to run it through our CI and then I can merge.

**Review by deadeyegoodwin — APPROVED** [review]

**Pull request merged**
