### PR TITLE
Fix gTest build

### PR DESCRIPTION
**Pull request by GuanLuo**

### CODE REVIEW

**Review by jbkyang-nvi — DISMISSED** [review]
thanks :D

**Review by CoderHam — APPROVED** [review]

**Review by rmccorm4 — DISMISSED** [review]

**Comment by rmccorm4** [comment]
Not asking for change, but for future reference this issue might've been resolved upstream: https://github.com/google/googletest/issues/2174

**Comment by GuanLuo** [comment]
Thanks for the pointer, added note regarding the fix.

**Review by jbkyang-nvi — APPROVED** [review]
create ticket?

**Review by rmccorm4 — APPROVED** [review]

**Comment by GuanLuo** [comment]
These libraries are obtained from the grpc repo for convenience. So we will check that along the way when we decide to advance grpc version used.

**Pull request merged**
